version: "3.8"

services:

  accounts:
    image: janmejaya1234/ms-11:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
      - "8081:8080"
      - "8082:8080"
      - "8083:8080"
      - "8084:8080"
      - "8085:8080"
    networks:
      - eazybank-network
networks:
  eazybank-network: